language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
install: COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install
script: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - vendor/bin/test-reporter
